# Generated by Django 4.0.1 on 2022-01-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_total_price_cart_total_cart_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
