# Generated by Django 4.0.1 on 2022-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_entry_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='product',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
