# Generated by Django 4.0.1 on 2022-01-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_entry_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
